import axios from 'axios'


const BACKEND_URL = 'https://rn-demo-course-default-rtdb.firebaseio.com/'

export function storeExpenese(expenseData){
    axios.post(BACKEND_URL + '/expenses.json',
    expenseData // object that holds the description,amount,data, unique id will be auto generated by firebase
    );
}

//get will give us access to fetch data from backend
export async function fetchExpenese(){
    const response = await axios.get(BACKEND_URL + '/expenses.json')

    const expenses = [];


 
for(const key in response.data){
    const expenseObj = {
        id:key,
        amount:response.data[key].amount,
        date:new Date(response.data[key].date),
        description:response.data[key].description
    }
    expenses.push(expenseObj)
}
return expenses
}

//Turn this into async function then we await this promise and store the eventually returned data
// which will be a response data we store in a constant. We get the response server.
